config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  devise_for :users, path: '', path_names: { sign_in: 'login',
                                             sign_out: 'logout',
                                             sign_up: 'register' }

  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'tech-news', to: 'pages#tech_news'

  resources :topics, only: [:index, :show]
  resources :blogs do
    member do
      get :toggle_status
    end
  end


  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end

  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  mount ActionCable.server => '/cable'
end

app/models/blog.rb
class Blog < ApplicationRecord
  enum status: { draft: 0, published: 1 }

  extend FriendlyId
  friendly_id :title, use: :slugged

  belongs_to :topic
  has_many :comments, dependent: :destroy

  scope :recent, -> { order(created_at: :desc) }
  validates_presence_of :title, :body, :topic_id
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:edit, :update, :destroy, :toggle_status]
  before_action :set_sidebar_topics, except: [:update, :create, :destroy, :toggle_status]
  layout 'blog'
  access all: [:show, :index], user: { except: [:new, :create, :update, :edit, :destroy, :toggle_status] }, site_admin: :all

  def index
    @blogs = if logged_in?(:site_admin)
               Blog.recent.page(params[:page]).per(5)
             else
               Blog.published.recent.page(params[:page]).per(5)
             end
  end

  def show
    @blog = Blog.includes(:comments).friendly.find(params[:id])

    if logged_in?(:site_admin) || @blog.published?
      @comment = Comment.new
    else
      flash[:notice] = 'You are not authorized to access this page'
      redirect_to blogs_path
    end
  end

  def new
    @blog = Blog.new
  end

  def edit;
  end

  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def toggle_status
    if @blog.draft?
      @blog.published!
      flash[:notice] = 'Blog is published!'
    elsif @blog.published?
      @blog.draft!
      flash[:notice] = 'Blog is in draft mode!'
    end
    redirect_to blogs_path
  end

  private

  def set_blog
    @blog = Blog.friendly.find(params[:id])
  end

  def blog_params
    params.require(:blog).permit(:title, :body, :topic_id, :status)
  end

  def set_sidebar_topics
    @side_bar_topics = Topic.with_blogs
  end
end

app/helpers/blogs_helper.rb
module BlogsHelper
  def gravatar_helper user
    image_tag "https://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(user.email)}",
              width: 60
  end

  class CodeRayify < Redcarpet::Render::HTML
    def block_code(code, language)
      CodeRay.scan(code, language).div
    end
  end

  def markdown(text)
    coderayified = CodeRayify.new(filter_html: true, hard_wrap: true)

    options = {
        fenced_code_blocks: true,
        no_intra_emphasis: true,
        autolink: true,
        lax_html_blocks: true
    }

    markdown_to_html = Redcarpet::Markdown.new(coderayified, options)
    markdown_to_html.render(text).html_safe
  end
end

app/views/blogs/_admin_actions.html.erb
<% if logged_in?(:site_admin) %>
    <nav class="breadcrumb blogcrumb">
      <%= link_to fa_icon('file-text'), toggle_status_blog_path(blog), class: blog.status %>
      <%= link_to fa_icon('pencil-square-o'), edit_blog_path(blog) %>
      <%= link_to fa_icon('trash'), blog, method: :delete, data: { confirm: 'Are you sure?' } %>
    </nav>
<% end %>

app/views/blogs/_blog.html.erb
<div class="blog-post">

  <h2 class="blog-post-title">
    <%= link_to blog.title, blog %>
  </h2>

  <p class="blog-post-meta">
    Published <%= distance_of_time_in_words(blog.created_at, Time.zone.now) %> ago
  </p>

  <%= render partial: 'blogs/admin_actions', locals: { blog: blog } %>

  <p>
    <%= markdown blog.body %>
  </p>
</div>

app/views/blogs/_comment.html.erb
<div class="comment-card">
  <div class="card">
    <div class="card-block">
      <div class="row">
        <div class="col-md-1">
        </div>

        <div class="col-md-11">
          <%= comment.content %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/blogs/_form.html.erb
<%= simple_form_for(blog) do |f| %>
    <% if blog.errors.any? %>
        <%= errors_to_flash(blog) %>
    <% end %>
    <%= f.input :title, placeholder: 'Title' %>

    <%= f.input :topic_id, collection: Topic.all, label_method: :title %>

    <%= f.input :status, collection: Blog.statuses, as: :radio_buttons, value_method: :first, label: false %>

    <%= f.input :body, as: :text, input_html: { rows: 15, placeholder: 'Body' } %>

    <%= f.button :submit, class: 'btn btn-primary' %>
<% end %>

app/views/blogs/edit.html.erb
<div class="col-sm-8 blog-main">
  <h1>Editing Blog</h1>

  <%= render 'form', blog: @blog %>

  <%= link_to 'Show', @blog %> |
  <%= link_to 'Back', blogs_path %>
</div>

app/views/blogs/index.html.erb
<div class="col-sm-8 blog-main">
  <%= paginate @blogs %>

  <%= render @blogs %>

  <%= paginate @blogs %>
</div>

app/views/blogs/new.html.erb
<div class="col-sm-8 blog-main">
  <h1>New Blog</h1>

  <%= render 'form', blog: @blog %>

  <%= link_to 'Back', blogs_path %>
</div>

app/views/blogs/show.html.erb
<div class="col-sm-8 blog-main">

  <h2><%= @blog.title %></h2>

  <nav class="breadcrumb">
    <%= link_to 'Home', root_path, class: 'breadcrumb-item' %>
    <%= link_to @blog.topic.title, topic_path(@blog.topic), class: 'breadcrumb-item' %>
    <span class="breadcrumb-item active"><%= @blog.title %></span>

    <span class="pull-right">
      <%= link_to fa_icon('pencil-square-o'), edit_blog_path(@blog) if logged_in?(:site_admin) %>
      <%= link_to fa_icon('trash'), @blog, method: :delete, data: { confirm: 'Are you sure?'} if logged_in?(:site_admin) %>
    </span>
  </nav>

  <p>
    <%= @blog.topic.title %>
  </p>

  <%= link_to 'Edit', edit_blog_path(@blog) if logged_in?(:site_admin) %>

  <p>
    <%= markdown @blog.body %>
  </p>

  <%= render 'comments/comment_form' %>

  <div id="comments" data-blog-id="<%= @blog.id %>">
    <%= render @blog.comments %>
  </div>
</div>