config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  devise_for :users, path: '', path_names: { sign_in: 'login',
                                             sign_out: 'logout',
                                             sign_up: 'register' }

  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'tech-news', to: 'pages#tech_news'

  resources :topics, only: [:index, :show]
  resources :blogs do
    member do
      get :toggle_status
    end
  end


  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end

  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  mount ActionCable.server => '/cable'
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  has_many :technologies, inverse_of: :portfolio
  accepts_nested_attributes_for :technologies,
                                allow_destroy: true,
                                reject_if: proc { |attributes| attributes['name'].blank? }

  validates_presence_of :title, :subtitle, :body, :technologies
  mount_uploader :thumb_image, PortfolioUploader
  mount_uploader :main_image, PortfolioUploader

  scope :ruby_on_rails, -> { where(subtitle: 'Ruby On Rails') }
  scope :vue, -> { where(subtitle: 'VueJS') }
  scope :by_position, -> {}
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  before_action :find_portfolio_item, only: [:show, :edit, :update, :destroy]
  layout 'portfolio'
  access all: [:show, :index], user: { except: [:new, :create, :update, :edit, :destroy, :sort] }, site_admin: :all

  def index
    @portfolio_items = Portfolio.by_position
  end

  def show;
  end

  def new
    @portfolio_item = Portfolio.new
  end

  def create
    @portfolio_item = Portfolio.new portfolio_item_params
    if @portfolio_item.save
      flash[:notice] = 'Portfolio was created successfully'
      redirect_to portfolio_show_path(@portfolio_item)
    else
      flash.now[:alert] = 'Portfolio creation failed'
      render :new
    end
  end

  def edit;
  end

  def update
    if @portfolio_item.update portfolio_item_params
      flash[:notice] = 'Portfolio was updated successfully'
      redirect_to portfolio_show_path(@portfolio_item)
    else
      flash.now[:alert] = 'Portfolio update failed'
      render :edit
    end
  end

  def destroy
    if @portfolio_item.destroy
      flash[:notice] = 'Portfolio was deleted successfully'
      redirect_to portfolios_path
    end
  end

  def sort
    params[:order].each do |key, value|
      Portfolio.find(value[:id]).update(position: value[:position])
    end
    render nothing: true
  end

  private

  def find_portfolio_item
    @portfolio_item = Portfolio.find(params[:id])
  end

  def portfolio_item_params
    params.require(:portfolio).permit(:title, :subtitle, :body,
                                      :main_image, :thumb_image,
                                      technologies_attributes: [:id, :name, :_destroy])
  end
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
  def image_generator(width:, height:)
    "http://placehold.it/#{width}x#{height}"
  end

  def portfolio_img(img, type)
    if img.model.main_image? || img.model.thumb_image?
      img
    elsif type == 'thumb'
      image_generator(height: '200', width: '350')
    elsif type == 'main'
      image_generator(height: '400', width: '600')
    end
  end
end

app/views/portfolios/_form.html.erb
<%= simple_form_for(@portfolio_item, html: { multipart: true, class: 'form-horizontal' }) do |f| %>
    <% if @portfolio_item.errors.any? %>
        <%= errors_to_flash(@portfolio_item) %>
    <% end %>
    <div class="row">
      <div class="col-md-6">
        <h3>Portfolio Content:</h3>
        <%= f.input :title %>
        <%= f.input :subtitle %>
        <label class="btn btn-primary">
          Upload a thumb image
          file <%= f.input :thumb_image, as: :file, label: false, input_html: { style: 'display: none;' } %>
        </label>
        <label class="btn btn-primary">
          Upload a main image file <%= f.input :main_image, as: :file, label: false, input_html: { hidden: true } %>
        </label>
        <%= f.input :body, as: :text, input_html: { rows: 10 } %>
      </div>
      <div class="col-md-6">
        <h3>Technologies Used:</h3>
        <div class="technologies">
          <%= f.simple_fields_for :technologies do |t| %>
              <%= render 'technology_fields', f: t %>
          <% end %>

          <div class="links">
            <%= link_to_add_association 'add technology', f, :technologies %>
          </div>
        </div>
      </div>
      <div class="col-md-12">
        <%= f.button :submit, 'Save', class: 'btn btn-primary btn-block' %>
      </div>
    </div>
<% end %>

app/views/portfolios/_portfolio_item.html.erb
<div class="col-md-4">
  <div class="card" data-id="<%= portfolio_item.id %>">
    <%= link_to portfolio_show_path(portfolio_item) do %>
        <%= image_tag portfolio_img(portfolio_item.thumb_image, 'thumb'), width: '100%' %>
    <% end %>
    <p class="card-text">
      <span><%= link_to portfolio_item.title, portfolio_show_path(portfolio_item) %></span> <%= portfolio_item.subtitle %>
    </p>
  </div>
</div>

app/views/portfolios/_technology_fields.html.erb
<div class="nested-fields">
  <%= f.input :name, required: true %>
  <%= link_to_remove_association 'remove technology', f %>
</div>

app/views/portfolios/edit.html.erb
<div class="container portfolio-container">
  <h1>Edit Porfolio Item</h1>
  <%= render 'form' %>
</div>

app/views/portfolios/index.html.erb
<div class="album text-muted">
  <div class="container">
    <%= source_helper('alert alert-warning') %>
    <div class="row <%= "sortable" if logged_in?(:site_admin) %>">
      <%= render partial: 'portfolio_item', collection: @portfolio_items %>
    </div>
  </div>
</div>

app/views/portfolios/new.html.erb
<div class="container portfolio-container">
  <h1>New Portfolio Item</h1>
  <%= render 'form' %>
</div>

app/views/portfolios/show.html.erb
<div class="container portfolio-container">
  <div class="row">
    <div class="col-md-7">
      <%= image_tag portfolio_img(@portfolio_item.main_image, 'main'), width: '100%' %>
    </div>
    <div class="col-md-5">
      <h1><%= @portfolio_item.title %></h1>
      <hr>
      <em><%= @portfolio_item.subtitle %></em>
      <p><%= @portfolio_item.body %></p>
      <hr>
      <h3>Technologies used:</h3>

      <% @portfolio_item.technologies.each do |technology| %>
          <p><%= technology.name %></p>
      <% end %>
      <% if logged_in?(:site_admin) %>
        <div>
          <%= link_to 'Edit Item', edit_portfolio_path(@portfolio_item), class: 'btn-sm btn-success' %>
        </div>
      <% end %>
    </div>
  </div>
</div>